
Set-Location c:\MimDsc

#region Call the Set and Test methods directly - allows for setting a breakpoint for debuggering
ipmo MimDsc -Force
ipmo 'C:\Program Files\WindowsPowerShell\Modules\MimDsc\DSCResources\MimSvcFilterScope\MimSvcFilterScope.psm1' -Force
psedit 'C:\Program Files\WindowsPowerShell\Modules\MimDsc\DSCResources\MimSvcFilterScope\MimSvcFilterScope.psm1'
psedit 'C:\Program Files\WindowsPowerShell\Modules\MimDsc\Functions\Test-MimSvcTargetResource.ps1'


$resourceProperties = @{
    DisplayName					= 'Administrator Filter Permission'
    AllowedAttributes           = @(
                                            'AccountName'
                                            'ActionParameter'
                                            'ActionType'
                                            'ActionWorkflowInstance'
                                            'ActionWorkflowDefinition'
                                            'ActivityName'
                                            'AD_UserCannotChangePassword'
                                            'Address'
                                            'AllowedAttributes'
                                            'AllowedMembershipReferences'
                                            'AppliesToCreate'
                                            'AppliesToEdit'
                                            'AppliesToView'
                                            'Approval'
                                            'ApprovalDuration'
                                            'ApprovalResponse'
                                            'ApprovalStatus'
                                            'ApprovalThreshold'
                                            'Approver'
                                            'Assembly'
                                            'AssemblyName'
                                            'Assistant'
                                            'SearchScopeColumn'
                                            'Required'
                                            'SearchScopeContext'
                                            'BoundAttributeType'
                                            'AuthenticationWorkflowInstance'
                                            'AuthenticationWorkflowDefinition'
                                            'AuthNWFLockedOut'
                                            'AuthNWFRegistered'
                                            'AuthorizationWorkflowInstance'
                                            'AuthorizationWorkflowDefinition'
                                            'EmailBody'
                                            'BrandingCenterText'
                                            'BrandingLeftImage'
                                            'BrandingRightImage'
                                            'City'
                                            'ClearRegistration'
                                            'CommittedTime'
                                            'Company'
                                            'ComputedActor'
                                            'ComputedMember'
                                            'ConfigurationData'
                                            'Connector'
                                            'ConstantValueKey'
                                            'ContactSet'
                                            'CostCenter'
                                            'CostCenterName'
                                            'Country'
                                            'CreateConnectedSystemObject'
                                            'CreateILMObject'
                                            'CreatedTime'
                                            'Creator'
                                            'FlowType'
                                            'DataType'
                                            'msidmDataWarehouseBindingIdentity'
                                            'msidmDataWarehouseMapping'
                                            'Decision'
                                            'DeletedTime'
                                            'Department'
                                            'Dependency'
                                            'Description'
                                            'DetectedRulesList'
                                            'Disabled'
                                            'DisconnectConnectedSystemObject'
                                            'DisplayName'
                                            'DisplayedOwner'
                                            'DistributionListDomain'
                                            'Domain'
                                            'DomainConfiguration'
                                            'Email'
                                            'MailNickname'
                                            'EmployeeEndDate'
                                            'EmployeeID'
                                            'EmployeeStartDate'
                                            'EmployeeType'
                                            'EndpointAddress'
                                            'ExistenceTest'
                                            'ExpectedRuleEntryAction'
                                            'ExpectedRulesList'
                                            'ExpirationTime'
                                            'ConnectedSystem'
                                            'ConnectedObjectType'
                                            'ConnectedSystemScope'
                                            'OfficeFax'
                                            'Filter'
                                            'ILMObjectType'
                                            'FirstName'
                                            'ForeignSecurityPrincipalSet'
                                            'ForestConfiguration'
                                            'FreezeCount'
                                            'FreezeLevel'
                                            'FunctionName'
                                            'GateData'
                                            'GateID'
                                            'GateTypeId'
                                            'UICacheTime'
                                            'GrantRight'
                                            'HasCollateralRequest'
                                            'ImageUrl'
                                            'InitialFlow'
                                            'IntegerMaximum'
                                            'IntegerMinimum'
                                            'IsActionActivity'
                                            'IsAuthenticationActivity'
                                            'IsAuthorizationActivity'
                                            'IsConfigurationType'
                                            'JobTitle'
                                            'LastName'
                                            'LastResetAttemptTime'
                                            'ListViewCacheTimeOut'
                                            'ListViewPageSize'
                                            'ListViewPagesToCache'
                                            'Locale'
                                            'Localizable'
                                            'AuthNLockoutRegistrationID'
                                            'LoginName'
                                            'ManagementPolicy'
                                            'Manager'
                                            'ExplicitMember'
                                            'MembershipAddWorkflow'
                                            'MembershipLocked'
                                            'MiddleName'
                                            'MobilePhone'
                                            'Multivalued'
                                            'MVObjectID'
                                            'Name'
                                            'Namespace'
                                            'UICountCacheTime'
                                            'NavigationPage'
                                            'NavigationUrl'
                                            'OfficeLocation'
                                            'OfficePhone'
                                            'Operation'
                                            'Order'
                                            'Owner'
                                            'FunctionParameters'
                                            'ParentOrder'
                                            'ParentRequest'
                                            'UIUserCacheTime'
                                            'PersistentFlow'
                                            'Photo'
                                            'PostalCode'
                                            'Precedence'
                                            'PrincipalSet'
                                            'PrincipalRelativeToResource'
                                            'ProxyAddressCollection'
                                            'IsRASEnabled'
                                            'Reason'
                                            'SearchScopeTargetURL'
                                            'Region'
                                            'Register'
                                            'RegistrationRequired'
                                            'RelationshipCriteria'
                                            'Request'
                                            'RequestControl'
                                            'RequestParameter'
                                            'RequestPhase'
                                            'RequestStatus'
                                            'RequestStatusDetail'
                                            'Requestor'
                                            'ResetPassword'
                                            'CountXPath'
                                            'ResourceCurrentSet'
                                            'ResourceFinalSet'
                                            'ObjectID'
                                            'ResourceParent'
                                            'ObjectSID'
                                            'ResourceTime'
                                            'BoundObjectType'
                                            'ObjectType'
                                            'SearchScopeResultObjectType'
                                            'RetentionPeriod'
                                            'ReturnType'
                                            'Rules'
                                            'RunOnPolicyUpdate'
                                            'Scope'
                                            'SearchScope'
                                            'SIDHistory'
                                            'StatusError'
                                            'StringRegex'
                                            'StringResources'
                                            'EmailSubject'
                                            'SupportedLanguageCode'
                                            'SyncConfig-attribute-inclusion'
                                            'SyncConfig-capabilities-mask'
                                            'SyncConfig-category'
                                            'SyncConfig-component_mappings'
                                            'SyncConfig-controller-configuration'
                                            'SyncConfig-creation-time'
                                            'SyncConfig-dn-construction'
                                            'SyncConfig-encrypted-attributes'
                                            'SyncConfig-export-attribute-flow'
                                            'SyncConfig-export-type'
                                            'SyncConfig-extension'
                                            'SyncConfig-format-version'
                                            'SyncConfig-id'
                                            'SyncConfig-import-attribute-flow'
                                            'SyncConfig-internal-version'
                                            'SyncConfig-join'
                                            'SyncConfig-last-modification-time'
                                            'SyncConfig-ma-companyname'
                                            'SyncConfig-ma-listname'
                                            'SyncConfig-ma-partition-data'
                                            'SyncConfig-ma-run-data'
                                            'SyncConfig-ma-ui-settings'
                                            'SyncConfig-mv-deletion'
                                            'SyncConfig-password-change-history-size'
                                            'SyncConfig-password-sync'
                                            'SyncConfig-password-sync-allowed'
                                            'SyncConfig-private-configuration'
                                            'SyncConfig-projection'
                                            'SyncConfig-provisioning'
                                            'SyncConfig-provisioning-cleanup'
                                            'SyncConfig-provisioning-cleanup-type'
                                            'SyncConfig-provisioning-type'
                                            'SyncConfig-refresh-schema'
                                            'SyncConfig-schema'
                                            'SyncConfig-stay-disconnector'
                                            'SyncConfig-sub-type'
                                            'SyncConfig-version'
                                            'SynchronizationRuleData'
                                            'SynchronizationRuleID'
                                            'SynchronizationRuleName'
                                            'SynchronizationRuleParameters'
                                            'SynchronizationRuleStatus'
                                            'SynchronizeObjectType'
                                            'Target'
                                            'TargetObjectType'
                                            'EmailTemplateType'
                                            'Temporal'
                                            'TimeZone'
                                            'TimeZoneId'
                                            'TrustedForest'
                                            'Type'
                                            'TypeName'
                                            'UsageKeyword'
                                            'UserID'
                                            'WorkflowDefinition'
                                            'WorkflowInstance'
                                            'WorkflowStatus'
                                            'WorkflowStatusDetail'
                                            'XOML'
            )
    AllowedMembershipReferences = 'All Groups and Sets'
    Ensure						= 'Present'
}

Test-MimSvcTargetResource -ObjectType FilterScope -KeyAttributeName DisplayName -DscBoundParameters $resourceProperties -Verbose:$true

Set-MimSvcTargetResource -ObjectType FilterScope -KeyAttributeName DisplayName -DscBoundParameters $resourceProperties -Verbose:$true

#endregion

#region: Test for an existing FilterScope
Configuration TestFilterScope 
{ 

    Import-DscResource -ModuleName MimDsc

    Node (hostname) 
    { 
        FilterScope 'Administrator Filter Permission'
        {
            DisplayName					= 'Administrator Filter Permission'
            AllowedAttributes           = @(
                                            'AccountName'
                                            'ActionParameter'
                                            'ActionType'
                                            'ActionWorkflowInstance'
                                            'ActionWorkflowDefinition'
                                            'ActivityName'
                                            'AD_UserCannotChangePassword'
                                            'Address'
                                            'AllowedAttributes'
                                            'AllowedMembershipReferences'
                                            'AppliesToCreate'
                                            'AppliesToEdit'
                                            'AppliesToView'
                                            'Approval'
                                            'ApprovalDuration'
                                            'ApprovalResponse'
                                            'ApprovalStatus'
                                            'ApprovalThreshold'
                                            'Approver'
                                            'Assembly'
                                            'AssemblyName'
                                            'Assistant'
                                            'SearchScopeColumn'
                                            'Required'
                                            'SearchScopeContext'
                                            'BoundAttributeType'
                                            'AuthenticationWorkflowInstance'
                                            'AuthenticationWorkflowDefinition'
                                            'AuthNWFLockedOut'
                                            'AuthNWFRegistered'
                                            'AuthorizationWorkflowInstance'
                                            'AuthorizationWorkflowDefinition'
                                            'EmailBody'
                                            'BrandingCenterText'
                                            'BrandingLeftImage'
                                            'BrandingRightImage'
                                            'City'
                                            'ClearRegistration'
                                            'CommittedTime'
                                            'Company'
                                            'ComputedActor'
                                            'ComputedMember'
                                            'ConfigurationData'
                                            'Connector'
                                            'ConstantValueKey'
                                            'ContactSet'
                                            'CostCenter'
                                            'CostCenterName'
                                            'Country'
                                            'CreateConnectedSystemObject'
                                            'CreateILMObject'
                                            'CreatedTime'
                                            'Creator'
                                            'FlowType'
                                            'DataType'
                                            'msidmDataWarehouseBindingIdentity'
                                            'msidmDataWarehouseMapping'
                                            'Decision'
                                            'DeletedTime'
                                            'Department'
                                            'Dependency'
                                            'Description'
                                            'DetectedRulesList'
                                            'Disabled'
                                            'DisconnectConnectedSystemObject'
                                            'DisplayName'
                                            'DisplayedOwner'
                                            'DistributionListDomain'
                                            'Domain'
                                            'DomainConfiguration'
                                            'Email'
                                            'MailNickname'
                                            'EmployeeEndDate'
                                            'EmployeeID'
                                            'EmployeeStartDate'
                                            'EmployeeType'
                                            'EndpointAddress'
                                            'ExistenceTest'
                                            'ExpectedRuleEntryAction'
                                            'ExpectedRulesList'
                                            'ExpirationTime'
                                            'ConnectedSystem'
                                            'ConnectedObjectType'
                                            'ConnectedSystemScope'
                                            'OfficeFax'
                                            'Filter'
                                            'ILMObjectType'
                                            'FirstName'
                                            'ForeignSecurityPrincipalSet'
                                            'ForestConfiguration'
                                            'FreezeCount'
                                            'FreezeLevel'
                                            'FunctionName'
                                            'GateData'
                                            'GateID'
                                            'GateTypeId'
                                            'UICacheTime'
                                            'GrantRight'
                                            'HasCollateralRequest'
                                            'ImageUrl'
                                            'InitialFlow'
                                            'IntegerMaximum'
                                            'IntegerMinimum'
                                            'IsActionActivity'
                                            'IsAuthenticationActivity'
                                            'IsAuthorizationActivity'
                                            'IsConfigurationType'
                                            'JobTitle'
                                            'LastName'
                                            'LastResetAttemptTime'
                                            'ListViewCacheTimeOut'
                                            'ListViewPageSize'
                                            'ListViewPagesToCache'
                                            'Locale'
                                            'Localizable'
                                            'AuthNLockoutRegistrationID'
                                            'LoginName'
                                            'ManagementPolicy'
                                            'Manager'
                                            'ExplicitMember'
                                            'MembershipAddWorkflow'
                                            'MembershipLocked'
                                            'MiddleName'
                                            'MobilePhone'
                                            'Multivalued'
                                            'MVObjectID'
                                            'Name'
                                            'Namespace'
                                            'UICountCacheTime'
                                            'NavigationPage'
                                            'NavigationUrl'
                                            'OfficeLocation'
                                            'OfficePhone'
                                            'Operation'
                                            'Order'
                                            'Owner'
                                            'FunctionParameters'
                                            'ParentOrder'
                                            'ParentRequest'
                                            'UIUserCacheTime'
                                            'PersistentFlow'
                                            'Photo'
                                            'PostalCode'
                                            'Precedence'
                                            'PrincipalSet'
                                            'PrincipalRelativeToResource'
                                            'ProxyAddressCollection'
                                            'IsRASEnabled'
                                            'Reason'
                                            'SearchScopeTargetURL'
                                            'Region'
                                            'Register'
                                            'RegistrationRequired'
                                            'RelationshipCriteria'
                                            'Request'
                                            'RequestControl'
                                            'RequestParameter'
                                            'RequestPhase'
                                            'RequestStatus'
                                            'RequestStatusDetail'
                                            'Requestor'
                                            'ResetPassword'
                                            'CountXPath'
                                            'ResourceCurrentSet'
                                            'ResourceFinalSet'
                                            'ObjectID'
                                            'ResourceParent'
                                            'ObjectSID'
                                            'ResourceTime'
                                            'BoundObjectType'
                                            'ObjectType'
                                            'SearchScopeResultObjectType'
                                            'RetentionPeriod'
                                            'ReturnType'
                                            'Rules'
                                            'RunOnPolicyUpdate'
                                            'Scope'
                                            'SearchScope'
                                            'SIDHistory'
                                            'StatusError'
                                            'StringRegex'
                                            'StringResources'
                                            'EmailSubject'
                                            'SupportedLanguageCode'
                                            'SyncConfig-attribute-inclusion'
                                            'SyncConfig-capabilities-mask'
                                            'SyncConfig-category'
                                            'SyncConfig-component_mappings'
                                            'SyncConfig-controller-configuration'
                                            'SyncConfig-creation-time'
                                            'SyncConfig-dn-construction'
                                            'SyncConfig-encrypted-attributes'
                                            'SyncConfig-export-attribute-flow'
                                            'SyncConfig-export-type'
                                            'SyncConfig-extension'
                                            'SyncConfig-format-version'
                                            'SyncConfig-id'
                                            'SyncConfig-import-attribute-flow'
                                            'SyncConfig-internal-version'
                                            'SyncConfig-join'
                                            'SyncConfig-last-modification-time'
                                            'SyncConfig-ma-companyname'
                                            'SyncConfig-ma-listname'
                                            'SyncConfig-ma-partition-data'
                                            'SyncConfig-ma-run-data'
                                            'SyncConfig-ma-ui-settings'
                                            'SyncConfig-mv-deletion'
                                            'SyncConfig-password-change-history-size'
                                            'SyncConfig-password-sync'
                                            'SyncConfig-password-sync-allowed'
                                            'SyncConfig-private-configuration'
                                            'SyncConfig-projection'
                                            'SyncConfig-provisioning'
                                            'SyncConfig-provisioning-cleanup'
                                            'SyncConfig-provisioning-cleanup-type'
                                            'SyncConfig-provisioning-type'
                                            'SyncConfig-refresh-schema'
                                            'SyncConfig-schema'
                                            'SyncConfig-stay-disconnector'
                                            'SyncConfig-sub-type'
                                            'SyncConfig-version'
                                            'SynchronizationRuleData'
                                            'SynchronizationRuleID'
                                            'SynchronizationRuleName'
                                            'SynchronizationRuleParameters'
                                            'SynchronizationRuleStatus'
                                            'SynchronizeObjectType'
                                            'Target'
                                            'TargetObjectType'
                                            'EmailTemplateType'
                                            'Temporal'
                                            'TimeZone'
                                            'TimeZoneId'
                                            'TrustedForest'
                                            'Type'
                                            'TypeName'
                                            'UsageKeyword'
                                            'UserID'
                                            'WorkflowDefinition'
                                            'WorkflowInstance'
                                            'WorkflowStatus'
                                            'WorkflowStatusDetail'
                                            'XOML'
            )
            AllowedMembershipReferences = 'All Groups and Sets'
            Ensure						= 'Present'
        }
    } 
} 

TestFilterScope

Start-DscConfiguration -Wait -Verbose -Path "C:\MimDsc\TestFilterScope" -Force
#endregion

#region: New FilterScope
$randomNumber = Get-Random -Minimum 100 -Maximum 999
Configuration TestFilterScope 
{ 

    Import-DscResource -ModuleName MimDsc

    Node (hostname) 
    { 
        FilterScope "TestFilterScope$randomNumber"
        {
            DisplayName					= "FilterScope$randomNumber"
            AllowedAttributes           = 'FreezeLevel','Description'
            Ensure						= 'Present'
        }
    } 
} 

TestFilterScope

Start-DscConfiguration -Wait -Verbose -Path "C:\MimDsc\TestFilterScope" -Force
#endregion

#region: Update FilterScope
$randomNumber = Get-Random -Minimum 100 -Maximum 999
Configuration TestFilterScope 
{ 

    Import-DscResource -ModuleName MimDsc

    Node (hostname) 
    { 
        FilterScope "TestFilterScope$randomNumber"
        {
            DisplayName					= "FilterScope$randomNumber"
            AllowedAttributes           = 'FreezeLevel','Description'
            Ensure						= 'Present'
        }
    } 
} 

TestFilterScope

Start-DscConfiguration -Wait -Verbose -Path "C:\MimDsc\TestFilterScope" -Force

Configuration TestFilterScope 
{ 

    Import-DscResource -ModuleName MimDsc

    Node (hostname) 
    { 
        FilterScope "TestFilterScope$randomNumber"
        {
            DisplayName					= "FilterScope$randomNumber"
            AllowedAttributes           = 'FreezeLevel','DisplayName'
            Ensure						= 'Present'
        }
    } 
} 

TestFilterScope

Start-DscConfiguration -Wait -Verbose -Path "C:\MimDsc\TestFilterScope" -Force

#endregion
