
[ClassVersion("1.0.0.0"), FriendlyName("Person")]
class MimSvcPerson : OMI_BaseResource
{
	[Key] String AccountName;
	[Write] Boolean AD_UserCannotChangePassword;
	[Write] String Address;
	[Write] String Assistant;
	[Write] String Attribute114;
	[Write] String Attribute339;
	[Write] String Attribute743;
	[Write] String AuthNWFLockedOut[];
	[Write] String AuthNWFRegistered[];
	[Write] String City;
	[Write] String Company;
	[Write] String CostCenter;
	[Write] String CostCenterName;
	[Write] String Country;
	[Read] DateTime CreatedTime;
	[Read] String Creator;
	[Read] DateTime DeletedTime;
	[Write] String Department;
	[Write] String Description;
	[Write] String DetectedRulesList[];
	[Write] String DisplayName;
	[Write] String Domain;
	[Write] String DomainConfiguration;
	[Write] String Email;
	[Write] String MailNickname;
	[Write] DateTime EmployeeEndDate;
	[Write] String EmployeeID;
	[Write] DateTime EmployeeStartDate;
	[Write] String EmployeeType;
	[Write] String ExpectedRulesList[];
	[Write] DateTime ExpirationTime;
	[Write] String OfficeFax;
	[Write] String FirstName;
	[Write] Uint64 FreezeCount;
	[Write] String FreezeLevel;
	[Write] String JobTitle;
	[Write] String LastName;
	[Write] DateTime LastResetAttemptTime;
	[Write] String Locale;
	[Write] String AuthNLockoutRegistrationID[];
	[Write] String LoginName;
	[Write] String Manager;
	[Write] String MiddleName;
	[Write] String MobilePhone;
	[Write] String MVObjectID;
	[Write] String OfficeLocation;
	[Write] String OfficePhone;
	[Write] String msidmOneTimePasswordEmailAddress;
	[Write] String msidmOneTimePasswordMobilePhone;
	[Write] String Photo;
	[Write] String PostalCode;
	[Write] String ProxyAddressCollection[];
	[Write] Boolean IsRASEnabled;
	[Write] Boolean Register;
	[Write] Boolean RegistrationRequired;
	[Write] String ResetPassword;
	[Read] String ObjectID;
	[Write] String ObjectSID;
	[Read] DateTime ResourceTime;
	[Read] String ObjectType;
	[Write] String SIDHistory[];
	[Write] String TimeZone;
	[Write, EmbeddedInstance("MSFT_Credential")] String Credential;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};