
[ClassVersion("1.0.0.0"), FriendlyName("DomainConfiguration")]
class MimSvcDomainConfiguration : OMI_BaseResource
{
	[Read] DateTime CreatedTime;
	[Read] String Creator;
	[Read] DateTime DeletedTime;
	[Write] String Description;
	[Write] String DetectedRulesList[];
	[Key] String DisplayName;
	[Write] String Domain;
	[Write] String ExpectedRulesList[];
	[Write] DateTime ExpirationTime;
	[Write] String ForeignSecurityPrincipalSet;
	[Write] String ForestConfiguration;
	[Write] Boolean IsConfigurationType;
	[Write] String Locale;
	[Write] String MVObjectID;
	[Read] String ObjectID;
	[Read] DateTime ResourceTime;
	[Read] String ObjectType;
	[Write, EmbeddedInstance("MSFT_Credential")] String Credential;
	[Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
